name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to your main branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'  # Specify your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test  # Make sure you have tests set up

    - name: Build application
      run: npm run build  # If applicable

    - name: Deploy to GCP
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "$GCP_SERVICE_ACCOUNT_KEY" > /tmp/gcp-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
        gcloud config set project $GCP_PROJECT_ID
        gcloud compute ssh your-username@your-instance-name --zone your-zone --command 'cd /path/to/your/app && git pull && npm install && npm start'
