name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this if your main branch is named differently
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Adjust this if you have different test commands
      
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures the build job is completed before deploying
    if: github.ref == 'refs/heads/main'  # Only deploy on main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy to GCP
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          # Write the service account key to a file
          echo "${{ secrets.GCP_SA_KEY }}" | jq . > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
          gcloud config set project $GCP_PROJECT_ID
          gcloud compute ssh vineet@instance-preprod --zone asia-south2-c --command "cd /home/vineet/SabhyashaPreProd && git pull && npm install && pm2 restart index.js"
